### ISSUE TITLE
isa_ok - Missunderstanding?

### ISSUE THREAD

**Issue by dannymk** [Test-More/Test2-Suite#165]
Am I getting this right?

============ TestInstance.pm
```
package TestInstance;
use Moose;
use namespace::autoclean;

has 'name' => (isa => 'Str', is=>'rw', default => 'Perl Test2');

__PACKAGE__->meta->make_immutable;

1;
```

============ TestInstance.t
```
use strict;
use Test2::Bundle::More;
use TestInstance;

plan 1;

isa_ok(TestInstance->new(), 'TestInstance', 'Create instance');
```

============= Results...

```
prove -I. TestInstance.t                                                                                                 
TestInstance.t .. 1/1 
# Failed test 'TestInstance=HASH->isa(...)'
# at TestInstance.t line 7.
# Failed: TestInstance=HASH->isa('Create instance')
TestInstance.t .. Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests 

Test Summary Report
-------------------
TestInstance.t (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
Files=1, Tests=1,  0 wallclock secs ( 0.02 usr  0.00 sys +  0.18 cusr  0.00 csys =  0.20 CPU)
Result: FAIL
.................
```

I am trying to convert my Test::More suite to Test2::...
however I am finding it a bit difficult to navigate these simple tests.

Any insight will be greatly appreciated.

**Comment by exodist** [comment]
The problem is in your original code. isa_ok from Test::More has this signature: `isa_ok($thing, $class, $alt_name_for_thing)` The third argument IS NOT a name for the assertion. This is an inconsistency against everything else Test::More exports. It is also bad because it will still pass if you use it incorrectly.

In Test2 I changed the signature to be consistent with `can_ok()`. The signature is now `isa_ok($thing, $class1, $class2, ...)` your test is now failing because it is trying to use "Create instance" as a class name. There is also an alternate signature you can use to get the job done: `isa_ok($thing, [$class], "Create Instance")` In this form the second argument is an arrayref full of class names, and the third argument is an assertion name.
