### ISSUE TITLE
can_ok does not work for AUTOLOD methods

### ISSUE THREAD

**Issue by j1n3l0** [Test-More/Test2-Suite#172]
Hi,

I'm not sure if this was intended but it would appear that I cannot test for `AUTOLOAD`ed methods using `can_ok`:

```
use Test2::V0;

sub AUTOLOAD {}

can_ok( __PACKAGE__, ['some_method'], 'AUTOLOAD methods are testable with "can_ok"' );

done_testing;
```

Please ignore if this was intentional but this cost me a good amount of time today.

**Comment by exodist** [comment]
It is not so much intentional as it is a consequence of perl.

the can_ok function tests that ```$x->can('thing')``` returns a truthy value (usually the coderef to the sub of the given name). In the case of AUTOLOAD without an override to `can()` ```$x->can('thing')``` will return undef. If the AUTOLOAD method injects the coderef into the package namespace then can() will start returning true after the first call to the specified sub.

So there is no bug here, ```$x->can('thing')``` returns false, so the assertion fails, per spec. The issue is that AUTOLOAD and can() are not smart enough on their own to be aware of the situation. A good and common practice to solve this problem is to also override `can()` in the package that has an AUTOLOAD so that it will vivify and insert any subs that would be autoloaded, and return the coderef.

**Comment by dakkar** [comment]
@j1n3l0 a possibly better alternative to raw `AUTOLOAD` is [`AUTOCAN`](https://metacpan.org/pod/Autoload::AUTOCAN)

**Comment by j1n3l0** [comment]
Thanks for clarifying.
