### ISSUE TITLE
Can't use assertions inside mocked method

### ISSUE THREAD

**Issue by elcamlost** [Test-More/Test2-Suite#174]
Hi!

My case is a bit crazy, but I don't think that I'm doing something forbidden.

So, I have a test.

```perl
use Test2::V0;
use Test::Mojo;
use experimental 'signatures';

my $t = Test::Mojo->new('App');
my $mock = mock 'App::Model::Image' => (
    around => [
        get_image_response => sub ($orig, $url) {
            if ($url->host eq 'localhost' or $url->host eq '127.0.0.1') {
                $t->get_ok($url->path_query());
                return $t->tx->res;
            }
            return $orig->($url);
        }
    ],
);

my $minion = $t->app->minion;
$minion->reset;
...
$minion->perform_jobs() && sleep 5;
ok($minion->stats->{finished_jobs}, $enqueued, 'jobs done');
is($minion->stats->{failed_jobs}, 0, '0 jobs failed');
is($minion->stats->{active_jobs}, 0, '0 jobs are active');

done_testing();
```

This test is parsing images and create minified and cropped versions of those images.
I need to use get_ok method because of Mojolicious Test::Mojo internal logic - it manipulates with event loop, so without get_ok method incoming get query can't be processed.

 After done_testing, I got an error
```
< REASON >  job  1    Planned for 23 assertions, but saw 30
```

Because of 7 get_ok requests in mocked function.

If I'm using `plan(30);` in the end of file, I got an error
```
(  DIAG  )  job  1    Looks like you planned 30 tests but ran 23.
( FAILED )  job  1    t/01-Jakutia.t
< REASON >  job  1    Test script returned error (Code: 255)
```

If I'm using `plan(23);` in the end of file, I got the first error (saw more than planned).

So, two questions.

1. To me, inabiblity to use test assertions inside mocks is a bug. At least, it must be documented in Test2::Mock
2. Is there a way to pass the test without changing the logic? I guess, I can do something with Test2::Event::Plan, but it has no good example how to do it.

**Comment by exodist** [comment]
This problem is not caused by mocking. You said you have an event loop, so things are happening async, which means you have an ordering problem.

done_testing counts tests run and calls it the end, so with done_testing you are reporting the plan before the event loop is down, so it counts 23, then the other 7 events occur.

plan(30) sets the plan to 30, but in TAP a plan must either be the very first, or very last thing, if you are replacing done_testing() with plan(30) then you still have an ordering problem as the plan is in the middle of your results.

Your fix would be to call `plan(30)` at the very top of your file before any assertions are made.

This is not a bug in Test2, it is an event ordering issue.
