### ISSUE TITLE
Test2::Require::Module should act like Test::Needs

### ISSUE THREAD

**Issue by autarch** [Test-More/Test2-Suite#20]
Some notable differences ...

* Works around some brain damage in earlier Perl versions
* Exports a `test_needs` sub you can use in subtests, which is really nice

I think that's it, but @haarg might know other differences.

**Comment by haarg** [comment]
A few notable differences:

1. Test::Needs has three implementations.  Test2 based, Test::Builder based, and writing TAP manually.  I did this for backwards compatibility, and also as a speed optimization.  Since the most common use case will be skipping an entire test script, optimizing for load time in that case seems worthwhile.
2. The exported `test_needs` sub means you can not only skip in subtests, but you can also skip part way through a script.  The most complicated parts of the code are to match up plans with skip counts.
3. When the RELEASE_TESTING env var is set, it will fail rather than skip.

Not all of this will be applicable to something dedicated to the Test2 environment.

**Comment by exodist** [comment]
I don't think Test2 needs to duplicate Test::Needs, if it did then why would we need Test::Needs?

Test2::Require::Module is a quick tool for a simple specific use case. If you need the more complex use case then use the tool that was built for it.

Now, if there are bugs (not missing features) that I need to fix, and can look at Test::Needs for how to fix them, then please re-open with specifics.
