### ISSUE TITLE
Possible to mock CORE sub?

### ISSUE THREAD

**Issue by sidey79** [Test-More/Test2-Suite#232]
Is it possible to Mock a core sub?

I've tried the following:
```
	my $mock_main = Test2::Mock->new(
		track => 1,
		class => 'main'
	);	 	

        $mock_core->override('readpipe' => sub {
                exit(127);
        });
```

This generates a Warning
`PERL WARNING: Prototype mismatch: sub CORE::readpipe (_) vs none at`

But when calling qx or readpipe directly this doesn't call the mocked readpipe sub.

**Comment by jkeenan** [comment]
On 2/3/21 4:30 PM, sidey79 wrote:
> Is it possible to Mock a core sub?
> 
> I've tried the following:
> 
> |my $mock_main = Test2::Mock->new( track => 1, class => 'main' ); 
> $mock_core->override('readpipe' => sub { exit(127); }); |
> 

use strict;

**Comment by exodist** [comment]
There are a couple things at play here, I will address them individually:

1) PERL WARNING: Prototype mismatch: sub CORE::readpipe (_) vs none at
You can fix this by adding the proper prototype to `readpipe => sub(ADD_PROTO_HERE) { exit(127) }`

2) The mocked sub is not used
This is because readpipe() is probably being bound at compile-time, then your override happens too-late at run-time. This is a harder problem to solve, you either need to mock in a BEGIN block before calling readpipe(), or add a custom readpipe() early in a begin block, then override its behavior as needed.

If the call to readpipe() is done in a different package than the override (IE the call is not in 'main') then your override will not work, you will instead need to override 'CORE::readpipe' or 'CORE::GLOBAL::readpipe' I cannot remember which. Also of note the override must happen BEFORE the file/module that does make the readpipe() call is compiled/loaded, or it needs to be done in a use/BEGIN block in that file/module.

Ultimately these test2 override tools were intended to override methods, which do not suffer from the compile-time/run-time and early binding issues. The same mechanisms can be used (and thus the tool can be used) to override functions and builtins, but the timing becomes something the think about and is easy to get wrong.

Unfortunately I do not have a recommended alternative apart from hand-coding your overrides at the proper times.

----

I am not sure what @jkeenan meant when he said to use strict, maybe he meant you would get better errors if you enabled it? I do not expect it to solve any of your problems here.

**Comment by sidey79** [comment]
I already using strict, but there was an error in my 1. Post. The mocking object is created like this:

```
	my $mock_core = Test2::Mock->new( $track => 1, class => 'CORE');	 	
```

**Comment by exodist** [comment]
Ah, you can ignore my comments about the 'main' package then as you were using core, but my comment still applies.

**Comment by jkeenan** [comment]
> [snip]

> I am not sure what @jkeenan meant when he said to use strict, maybe he meant you would get better errors if you enabled it? I do not expect it to solve any of your problems here.

I copied-and-pasted the OP's code exactly as written into a file.  I noticed that that code was not using either strictures or warnings.  I put both into the file.  Result:
```
Global symbol "$mock_core" requires explicit package name (did you forget to declare "my $mock_core"?) at mock.pl line 8.
Execution of mock.pl aborted due to compilation errors.
```

**Comment by sidey79** [comment]
@exodist 

It makes sens and i think i got the relevant points.

Something like the following shoud work i think, but in my scenario module which calls readpipe is compiled before i can cause this begin block.
Putting the mocking in my production code seems not really to be an solution. But i now have another idea how i can run my test. :)


```
BEGIN {

	$mock_core = Test2::Mock->new(
		track => 1,
		class => 'CORE'
	);	 	

    $mock_core->override(readpipe => sub {
        exit(127);
    } );



};
```

**Comment by exodist** [comment]
I am glad I was able to convey the issue sufficiently for you to adjust your plan :-).  Please close the ticket when/if you are satisfied with the results/answers.
