### ISSUE TITLE
perltidyrc doesn’t match code style, seems invalid and not be be applied or enforced

### ISSUE THREAD

**Issue by dboehmer** [Test-More/Test2-Suite#240]
I am working on a PR for #239 and tried to apply the [perltidyrc](https://github.com/Test-More/Test2-Suite/blob/master/perltidyrc) as a habbit. I found several issues:

* The `--nt` option isn’t documented and seems not to exist. I couldn’t find it in Perl-Tidy’s CHANGES.md either.
* You seem to prefer spaces over the tabs but `--entab-leading-whitespace=4` makes Perl-Tidy just produce tabs
* regardless of indentation a run of `perltidy` fixed a lot of other stuff like cuddled else
* I think neither default nor your custom rc settings have been applied for long. It’s also not enforced.

The file was added in 49fe55c7fab5373bccf91671b5accee4a9d44070 and never changed again or mentioned in any commit messages.

What is your current tidy regime?

**Comment by exodist** [comment]
here is my most recent one, yeah I usually use a system-wide one I have set up instead of commiting to the repos, so not sure why that is even in there.

`
--indent-columns=4               # size of indentation
--nt                             # no tabs
--continuation-indentation=4     # indentation of wrapped lines
--maximum-line-length=0          # max line length before wrapping (turn it off)
--nooutdent-long-quotes          # do not outdent overly long quotes
--paren-tightness=2              # no spacing for parentheses
--square-bracket-tightness=2     # no spacing for square brackets
--brace-tightness=2              # no spacing for hash curly braces
--block-brace-tightness=0        # spacing for coderef curly braces
--comma-arrow-breakpoints=1      # break long key/value pair lists
--break-at-old-comma-breakpoints # this attempts to retain list break points
--no-blanks-before-comments      # do not insert blank lines before comments
--indent-spaced-block-comments   # no blanks before comments
--nocuddled-else                 # Do not cuddle else
--nospace-for-semicolon          # no space before semicolons in loops
--nospace-terminal-semicolon     # no space before termonal semicolons
--notrim-qw                      # Do not mess with qw{} whitespace
--opening-token-right            # make "push @array, {" indent nicely
--converge                       # Run until the output stops changing
--extended-syntax                # For Fennec/Test2 and other Devel::Declare syntax tools
--no-outdent-labels              # Do not outdent labels
--wn
`

**Comment by dboehmer** [comment]
That still contains `--nt` which seems not to exist and then is a no-op. But this still helped me to format my PR. Thanks!

**Comment by exodist** [comment]
```
$ perltidy --help
[...]
Basic Options:
 -i=n    use n columns per indentation level (default n=4)
 -t      tabs: use one tab character per indentation level, not recommended
 -nt     no tabs: use n spaces per indentation level (default)
[...]
```

Also this if you meant to ask about --wn
```
-wn     weld nested: combines opening and closing tokens when both are adjacent
```
