### ISSUE TITLE
Please make plan() combatible with old-style plan()

### ISSUE THREAD

**Issue by petdance** [Test-More/Test2-Suite#25]
All my subtests have plans.

    subtest foo => sub {
        plan tests => 14;
    }

In order to use Test2::Tools::Basic, I would have to change all of those to:

    subtest foo => sub {
        plan 14;
    }

If you'd allow either

    plan tests => 14;
    plan 14;

then it would save me from changing 1500 plans in 400 different files.

It would also be nice if we could use

    use Test2::Bundle::Extended plan => 14;

just like we currently do

    use Test::More plan => 14;

**Comment by exodist** [comment]
There is no technical reason not to allow plan to understand the Test::More keywords 'tests' and 'skip_all', so I can go ahead and add that support, which will fix the main problem in this ticket.

There are however good technical reasons not to allow planning at import.

1) Test2::Util has the concept of plugins. Plugins are global behavioral changes. Some of these changes need to happen before any events are sent, and planning is an event. If I allowed planning at import it would mean that using it also forces you to list plugins before tools. Without this behavior they can be loaded in any order (simply loading Test2::API or Test2::Bundle::Extended) will not send events, and as such loading it does not force an API state.

2) skip-all plans inside subtests work by using 'last' to jump out of the skip-all code all the way up the stack to the subtest code. This is necessary because one common use case for subtests is to use 'do' to run a file, if we use exceptions for this flow control the 'do' will eat them. However if you plan at import it adds a BEGIN between the skip_all and the subtest implementation, and last cannot jump out of BEGIN due to a perl bug (https://rt.perl.org/Public/Bug/Display.html?id=123287).

Since migrating from Test::More to Test2::* is completely optional, I have, and will take liberty to do things differently if there are good technical reasons, or known problems with the way Test::More did things. This may be a burden on converting, but converting is optional. It will however provide a better experience when writing new tests (more for new users who don't have bad habits memorized, but old users are capable of learning)

Summary: Will add support for 'tests' and 'skip_all' being provided to plan(). Will not add planning at import.

**Comment by petdance** [comment]
Understood about the plugins.  `plan tests => x` was my big concern.  Thanks.
