### ISSUE TITLE
Please add prototypes to the comparison functions

### ISSUE THREAD

**Issue by petdance** [Test-More/Test2-Suite#26]
Function prototypes are a huge benefit when writing tests, because it's so easy to get the arguments goofed up.  You're thinking `cmp_ok` when writing `is`, and you do this:

    is( 'dog', '==', 'cat', 'Are dogs the same as cats?' );

Under Test2, the test will fail but the code will execute.

Using Test::More I would get:

    Too many arguments for Test::More::is at foo.pl line 7, near "'Are dogs the same as cats?' )"
    Execution of foo.pl aborted due to compilation errors.

Anything we can do to catch errors at compile time is a big win.

**Comment by exodist** [comment]
https://github.com/Test-More/Test2-Suite/blob/master/lib/Test2/Tools/Compare.pm#L73

They do have prototypes. They are just not the prototypes you expected. In Test2::Suite the tools have been given a slurpy @ at the end of the prototype so that you can add 1 or more diagnostics strings to render with any failure. In Test2 diagnostics are more closely tied to the failures, and this lets you links them easier.
