### ISSUE TITLE
cmp_ok() with non-integer numbers gives incorrect diagnostic output

### ISSUE THREAD

**Issue by petdance** [Test-More/Test2-Suite#53]
Call `cmp_ok` with integers and all is good.

````
$ perl -MTest2::Tools::ClassicCompare -E'cmp_ok( 1, ">", 4 )'
not ok 1
# Failed test at -e line 1.
# +-----+----+-------+
# | GOT | OP | CHECK |
# +-----+----+-------+
# | 1   | >  | 4     |
# +-----+----+-------+
````

But call it with decimals and you get this:

````
$ perl -MTest2::Tools::ClassicCompare -E'cmp_ok( 1.23456, ">", 4.5678 )'
not ok 1
# Failed test at -e line 1.
# +------+---------+----+--------+
# | TYPE | GOT     | OP | CHECK  |
# +------+---------+----+--------+
# | num  | 1       | >  | 4      |
# | orig | 1.23456 |    | 4.5678 |
# +------+---------+----+--------+
````

**Comment by exodist** [comment]
Looked into this when first reported tome moments ago. The compare logic is correct, this is a display error on failures.

https://metacpan.org/source/EXODIST/Test2-Suite-0.000055/lib/Test2/Tools/ClassicCompare.pm#L231

This logic is here to make sure a numeric operator gets diagnostics that show the thing being compared as it is seen when treated as a number. Similar thing happens for strings. This is because of dualvars which may be one thing when treated as a number, and another when treated as a string.

In this case the use of sprintf('%D') is wrong because it forces the number to be an integer.

**Comment by schwern** [comment]
I'm looking into this as an excuse to get my hands dirty with Test2 guts.
