### ISSUE TITLE
Allow `bag` to take an array ref.

### ISSUE THREAD

**Issue by schwern** [Test-More/Test2-Suite#57]
```
is $set, bag { item 1; item 2; item 3; end; };   # annoying
is $set, bag [1,2,3];  # easy

is [sort @thing], [sort @thing];  # annoying
is \@thing, bag \@thing;  # easy
```

**Comment by exodist** [comment]
We cannot do this without breaking the codeblock syntax since it uses a prototype. I know bag is already being used, and I like having the array form available.

3 possibilities:

1) A second function for bag

```is \@thing, to_bag(\@thing);```

Meh.

2) An 'items' function that lets you merge a list into either an array or a bag (at the current index for an array)

    bag { items @things };
    array { item 0 => 'first'; items @things; };

Maybe more verbose than you wanted, but makes it easier to add items to an array too.

3) Make the underlying code accept a coderef or an arrayref, but keep the prototype, telling people to use ```&bag(\@items)``` to bypass the prototype.

I would be surprised if anyone actually thinks this is a good idea.

**Comment by schwern** [comment]
`items`! Yes, oh holy cheese snacks! It will make `array` so much easier to use!

```
array { item 1; item 2; item "oh god"; item "please stop"; item "my fingers hurt"; };

array { items 1, 2, 3, 4, 5, 6 };
```
